# 网站基本信息
site_name: Torch-RecHub
site_url: https://datawhalechina.github.io/torch-rechub/
repo_url: https://github.com/datawhalechina/torch-rechub
site_description: A PyTorch-based recommender system framework providing easy-to-use and extensible solutions
site_author: Datawhale
copyright: "Copyright &copy; 2025 Datawhale"

# 主题设置
theme:
  name: material
  language: en
  features:
    - content.code.copy # 开启代码复制功能
    - navigation.tabs
    - navigation.top
    - navigation.expand
    - search.share
    - navigation.sections # 在左侧导航栏中自动展开当前页面所在的部分
    - toc.integrate # 将目录集成到左侧导航
    - navigation.top # 返回顶部按钮
    - search.suggest # 搜索建议
    - search.highlight # 搜索高亮
  palette:
    - scheme: auto
      primary: teal
      accent: orange
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono
  icon:
    repo: fontawesome/brands/github

# 导航结构
nav:
  - Home: en/index.md
  - Quick Start:
      - Installation Guide: en/installation.md
      - Getting Started Tutorial: en/getting-started.md
  - Introduction: en/introduction.md
  - Tutorials:
      - Ranking Models: en/tutorials/ranking.md
      - Matching Models: en/tutorials/matching.md
      - Multi-Task Learning: en/tutorials/multi-task.md
  - API Reference:
      - Models: en/api-reference/models.md
      - Trainers: en/api-reference/trainers.md
      - Utilities: en/api-reference/utils.md
  - Blog:
      - Match Blog: en/blog/match.md
      - Rank Blog: en/blog/rank.md
  - Examples: en/examples.md
  - FAQ: en/faq.md
  - Contribution Guide: en/contributing.md

# 插件设置
plugins:
  - search
  - awesome-pages
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          options:
            members: true
  - i18n:
      docs_structure: folder
      default_language: en
      languages:
        - language: zh
          name: 中文
          locale: zh
          build: true
          nav_translations:
            Home: 首页
            Quick Start: 快速开始
            Installation Guide: 安装指南
            Getting Started Tutorial: 入门教程
            Introduction: 项目介绍
            Tutorials: 教程
            Ranking Models: 排序模型
            Matching Models: 召回模型
            Multi-Task Learning: 多任务学习
            API Reference: API参考
            Models: 模型
            Trainers: 训练器
            Utilities: 工具类
            Examples: 示例
            FAQ: 常见问题
            Contribution Guide: 贡献指南
            Blog: 博客
            Match Blog: 召回博客
            Rank Blog: 排序博客
        - language: en
          name: English
          locale: en
          build: true
          default: true
      languages_dir: docs/
      nav_style: separate
      language_selector: true
      language_selector_position: header
      language_selector_name: "🌐"
      nav_translate: true # 启用导航翻译

# Markdown 扩展
markdown_extensions:
  - admonition # 启用警告框
  - tables # 启用表格
  - pymdownx.highlight # 启用代码高亮
  - pymdownx.superfences # 启用自定义代码块
  - pymdownx.details # 启用可折叠的详细信息
  - pymdownx.emoji: # 启用表情符号
  - pymdownx.inlinehilite # 启用行内代码高亮
  - pymdownx.arithmatex:
      generic: true # 启用数学公式

# 额外页面设置
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/datawhalechina/torch-rechub

extra_css:
  - theme/css/import.css #主题CSS
  - https://unpkg.com/katex@0/dist/katex.min.css # 数学公式支持

extra_javascript:
  - theme/js/zoom.js #主题JS
  - javascripts/tablesort.js # 表格排序支持
  - javascripts/tablesort.min.js # 表格排序支持

  # katex数学公式支持
  - javascripts/katex.js # 数学公式支持
  - javascripts/katex.min.js # 数学公式支持
  - javascripts/auto-render.min.js # 数学公式支持
